/qos_relay:
  ros__parameters:
    dua:
      tf_server:
        get_transform: false
        transform_pose: false
        wait_servers: false
    input:
      name: /input
      qos:
        depth: 10
        reliability: reliable
      wait: true
    output:
      name: /output
      qos:
        depth: 1
        reliability: best_effort
